version: "3.9"

services:
  db: 
    image: postgres 
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment: 
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}

volumes:
  postgres_data:
